# config.yaml
global:
  enabled: false
  image: "consul:1.6.2"
  datacenter: saban
  gossipEncryption: 
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
syncCatalog:
  enabled: true


client:
  enabled: true
  # Set this to true to expose the Consul clients using the Kubernetes node
  # IPs. If false, the pod IPs must be routable from the external servers.
  exposeGossipPorts: true
  join:
    - "provider=aws tag_key=consul_server tag_value=true"
dns:
  enabled: true

#connectInject:
#  enabled: true
#  default: true
