apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: index.docker.io/eransaban/final-app:latest
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: dbusername
              key: user
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: dbpassword
              key: password
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:  
  name: project-svc
spec:
  selector:    
    app: python
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP