- name: Configure Monitor server
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - external_vars.yml
  become: yes
  tasks:
     - name: Edit Notifiers page
       replace:
         path: /etc/grafana/provisioning/notifiers/notify.yaml
         after: https://hooks.slack.com/services/
         regexp: '^(.*changeme)$'
         replace: '{{slackhook}}'
       ignore_errors: yes
     - name: Restart Grafana Server
       service:
         name: grafana-server
         state: restarted
